spring:
  datasource:
    url: jdbc:h2:mem:ohouse
    username: sa
    password:
    driver-class-name: org.h2.Driver
  jpa:
    show-sql: true
    generate-ddl: true
    database: h2
    database-platform: org.hibernate.dialect.H2Dialect
    open-in-view: false
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
jwt:
  headerName: Authorization
  secretKey: ohouseTokenvalidate
file:
  dir: C:/users/Hanbin/files/
#  dir: src/main/resources/static/
app:
  host: http://localhost:8080/
cloud:
  aws:
    credentials:
      access-key:
      secret-key:
    region:
      static: ap-northeast-2
    s3:
      bucket:
    stack:
      auto: false